const WORDS = [
  {
    "word": "wireless mouse",
    "ipa": "/ˈwaɪər.ləs maʊs/",
    "translation": "无线鼠标",
    "pinyin": "wú xiàn shǔ biāo",
    "example1": "I use a Logitech G Pro X Superlight wireless mouse for gaming because it's lightweight and responsive.",
    "example1Translation": "我用罗技G Pro X Superlight无线鼠标玩游戏，因为它轻便且响应灵敏。",
    "example2": "This wireless mouse connects to the computer via Bluetooth.",
    "example2Translation": "这款无线鼠标通过蓝牙与电脑连接。",
    "extension": "罗技GPW系列，轻量化电竞鼠标，适用于游戏/办公",
    "category": "electronics"
  },
  {
    "word": "spicy and hot soup",
    "ipa": "/ˈspaɪ.si ənd hɒt suːp/",
    "translation": "胡辣汤",
    "pinyin": "hú là tāng",
    "example1": "Spicy and hot soup is a popular traditional breakfast in central China, especially in Henan province.",
    "example1Translation": "胡辣汤是中国中部地区（尤其是河南省）很受欢迎的传统早餐。",
    "example2": "We usually add some vinegar and sesame oil to the spicy and hot soup to enhance the flavor.",
    "example2Translation": "我们通常会在胡辣汤里加些醋和香油来提味。",
    "extension": "中国北方传统早餐，酸辣鲜香，含肉/菌菇等食材",
    "category": "food"
  },
  {
    "word": "urban building complex",
    "ipa": "/ˈɜː.bən ˈbɪl.dɪŋ ˈkɒm.pleks/",
    "translation": "城市建筑群",
    "pinyin": "chéng shì jiàn zhù qún",
    "example1": "The urban building complex integrates office spaces, residential areas and commercial facilities.",
    "example1Translation": "这片城市建筑群整合了办公空间、住宅区与商业设施。",
    "example2": "Modern urban building complexes often adopt glass curtain walls for better lighting.",
    "example2Translation": "现代城市建筑群常采用玻璃幕墙以获得更好的采光。",
    "extension": "城市核心区多功能建筑集合，含办公/居住/商业功能",
    "category": "architecture"
  },
  {
    "word": "mechanical keyboard",
    "ipa": "/məˈkæn.ɪ.kəl ˈkiː.bɔːd/",
    "translation": "机械键盘",
    "pinyin": "jī xiè jiàn pán",
    "example1": "This 68-key mechanical keyboard is popular among gamers for its compact design and responsive switches.",
    "example1Translation": "这款68键机械键盘凭借紧凑的设计和灵敏的轴体，受到游戏玩家的青睐。",
    "example2": "Many users prefer mechanical keyboards over membrane ones for their tactile feedback and durability.",
    "example2Translation": "相较于薄膜键盘，许多用户更偏爱机械键盘，因其具有触感反馈和耐用性。",
    "extension": "独立机械轴体，分68/87/104键配列，用于游戏/办公",
    "category": "electronics"
  },
  {
    "word": "smart speaker",
    "ipa": "/smɑːt ˈspiː.kə(r)/",
    "translation": "智能音箱",
    "pinyin": "zhì néng yīn xiāng",
    "example1": "You can control home appliances by giving voice commands to this smart speaker.",
    "example1Translation": "你可以通过向这款智能音箱发出语音指令来控制家电。",
    "example2": "This smart speaker supports high-quality audio playback and wireless connectivity.",
    "example2Translation": "这款智能音箱支持高品质音频播放与无线连接功能。",
    "extension": "集成语音助手，具备语音交互/智能家居控制功能",
    "category": "electronics"
  },
  {
    "word": "laptop",
    "ipa": "/ˈlæp.tɒp/",
    "translation": "笔记本电脑",
    "pinyin": "bǐ jì běn diàn nǎo",
    "example1": "I often use my laptop to handle work tasks and browse the internet when I'm on the go.",
    "example1Translation": "我外出时经常用笔记本电脑处理工作任务和浏览网络。",
    "example2": "This high-performance laptop is suitable for both gaming and professional software operation.",
    "example2Translation": "这款高性能笔记本电脑既适用于游戏，也能满足专业软件的运行需求。",
    "extension": "便携电子设备，分轻薄本/游戏本/商务本类型",
    "category": "electronics"
  },
  {
    "word": "electric kettle",
    "ipa": "/ɪˈlek.trɪk ˈket.l/",
    "translation": "电热水壶",
    "pinyin": "diàn rè shuǐ hú",
    "example1": "The electric kettle can boil water in just a few minutes, which is very convenient for making tea.",
    "example1Translation": "这款电热水壶几分钟就能把水烧开，用来泡茶非常方便。",
    "example2": "Most electric kettles are equipped with an automatic shut-off function for safety.",
    "example2Translation": "大多数电热水壶都配备了自动断电功能，以保障使用安全。",
    "extension": "快速加热液体，含自动断电/防干烧设计，用于家庭/办公",
    "category": "daily"
  },
  {
    "word": "ceramic cup",
    "ipa": "/səˈræm.ɪk kʌp/",
    "translation": "陶瓷杯",
    "pinyin": "táo cí bēi",
    "example1": "I like drinking tea with this delicate ceramic cup because it keeps the temperature well.",
    "example1Translation": "我喜欢用这个精致的陶瓷杯喝茶，因为它的保温效果很好。",
    "example2": "This ceramic cup with blue patterns and golden edges is both practical and decorative.",
    "example2Translation": "这个带有蓝纹和金边的陶瓷杯兼具实用性与装饰性。",
    "extension": "以陶瓷为材质，通常具备保温、易清洁的特点，部分带有装饰性花纹/金边设计，常用于饮水、泡茶",
    "category": "daily"
  },
  {
    "word": "tea cup",
    "ipa": "/ˈtiː kʌp/",
    "translation": "茶杯",
    "pinyin": "chá bēi",
    "example1": "She poured hot tea into the delicate teacup and enjoyed it slowly.",
    "example1Translation": "她把热茶倒进精致的茶杯里，慢慢享用。",
    "example2": "This tea cup with golden handle is not only beautiful but also comfortable to hold.",
    "example2Translation": "这个带金色杯柄的茶杯不仅美观，拿握起来也很舒适。",
    "extension": "通常为陶瓷材质，多带有装饰设计，主要用于盛放茶水，兼具实用性与观赏性，是中式茶饮文化中常见的器具",
    "category": "daily"
  }
];